#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# -----------  -----------------------------------------------------------
#        file  xpwg.py
# description  xkcd #936 style password generator
#     created  2013-04-23 XX:XX IST
#    modified  2016-11-23 17:24 IST
# -----------  -----------------------------------------------------------
#

import random
import sys

# http://www.desiquintans.com/downloads/nounlist.txt
WORDS = [
    'aardvark', 'abyssinian', 'accelerator', 'accept', 'accordion',
    'account', 'accountant', 'acknowledgment', 'acoustic', 'acrylic',
    'action', 'active', 'activity', 'actor', 'actress', 'adapter',
    'addition', 'address', 'adjustment', 'adult', 'advantage',
    'advertisement', 'advice', 'afghanistan', 'africa', 'aftermath',
    'afternoon', 'aftershave', 'afterthought', 'agenda', 'agreement',
    'airbus', 'airmail', 'airplane', 'airport', 'airship', 'alarm',
    'albatross', 'alcohol', 'algebra', 'algeria', 'alibi', 'alley',
    'alligator', 'allow', 'alloy', 'almanac', 'alphabet', 'aluminium',
    'aluminum', 'ambulance', 'america', 'american', 'amount', 'amusement',
    'anatomy', 'anethesiologist', 'anger', 'angle', 'angora', 'animal',
    'anime', 'ankle', 'answer', 'antarctica', 'anteater', 'antelope',
    'anthony', 'anthropology', 'apartment', 'apology', 'apparatus',
    'apparel', 'appeal', 'appendix', 'apple', 'appliance', 'approval',
    'april', 'aquarius', 'archaeology', 'archeology', 'archer',
    'architecture', 'argentina', 'argument', 'aries', 'arithmetic',
    'armadillo', 'armchair', 'armenian', 'arrow', 'ashtray', 'asparagus',
    'asphalt', 'asterisk', 'astronomy', 'athlete', 'attack', 'attempt',
    'attention', 'attic', 'attraction', 'august', 'australia',
    'australian', 'author', 'authorisation', 'authority', 'authorization',
    'available', 'avenue', 'babies', 'baboon', 'backbone', 'bacon',
    'badge', 'badger', 'bagel', 'bagpipe', 'baker', 'bakery', 'balance',
    'balinese', 'balloon', 'bamboo', 'banana', 'bandana', 'bangalore',
    'bangladesh', 'bangle', 'banjo', 'bankbook', 'banker', 'barbara',
    'barber', 'barge', 'baritone', 'barometer', 'baseball', 'basement',
    'basin', 'basket', 'basketball', 'bassoon', 'bathroom', 'bathtub',
    'battery', 'battle', 'beach', 'beard', 'beast', 'beautician',
    'beauty', 'beaver', 'bedroom', 'beech', 'beetle', 'beggar', 'begin',
    'beginner', 'begonia', 'behavior', 'belgian', 'belief', 'believe',
    'bench', 'bengal', 'beret', 'berry', 'bestseller', 'better', 'betty',
    'bibliography', 'bicycle', 'billboard', 'biology', 'biplane',
    'birch', 'birth', 'birthday', 'black', 'bladder', 'blade',
    'blanket', 'blinker', 'blizzard', 'block', 'blood', 'blouse',
    'blowgun', 'board', 'bobcat', 'bogota', 'bomber', 'bongo', 'bonsai',
    'bookcase', 'booklet', 'border', 'borrow', 'botany', 'bottle',
    'bottom', 'boundary', 'bowling', 'brace', 'bracket', 'brain',
    'brake', 'branch', 'brand', 'brandy', 'brass', 'brazil', 'bread',
    'break', 'breakfast', 'breath', 'brian', 'brick', 'bridge', 'bring',
    'british', 'broccoli', 'brochure', 'broker', 'bronze', 'brother',
    'brother-in-law', 'brown', 'brush', 'bubble', 'bucket', 'budget',
    'buffer', 'buffet', 'bugle', 'building', 'bulldozer', 'bumper',
    'burglar', 'burma', 'burst', 'business', 'butane', 'butcher',
    'butter', 'button', 'buzzard', 'cabbage', 'cabinet', 'cable',
    'cactus', 'calculator', 'calculus', 'calendar', 'camel', 'camera',
    'canada', 'canadian', 'cancel', 'cancer', 'candle', 'cannon',
    'canoe', 'canvas', 'capital', 'cappelletti', 'capricorn', 'captain',
    'caption', 'caravan', 'carbon', 'cardboard', 'cardigan', 'carnation',
    'carol', 'carpenter', 'carriage', 'carrot', 'cartoon', 'castanet',
    'catamaran', 'caterpillar', 'cathedral', 'catsup', 'cattle',
    'cauliflower', 'cause', 'caution', 'clamp', 'ceiling', 'celery',
    'celeste', 'cellar', 'cello', 'celsius', 'cement', 'cemetery',
    'centimeter', 'central', 'century', 'ceramic', 'cereal', 'certain',
    'certification', 'chain', 'chair', 'chalk', 'chance', 'change',
    'channel', 'character', 'chard', 'charles', 'chauffeur', 'check',
    'cheek', 'cheese', 'cheetah', 'chemistry', 'cheque', 'cherries',
    'cherry', 'chess', 'chest', 'chick', 'chicken', 'chicory',
    'chief', 'child', 'children', 'chill', 'chime', 'chimpanzee',
    'china', 'chinese', 'chive', 'chocolate', 'chord', 'christmas',
    'christopher', 'chronometer', 'church', 'cicada', 'cinema', 'circle',
    'circulation', 'cirrus', 'citizenship', 'clarinet', 'class',
    'claus', 'clave', 'clean', 'clear', 'clerk', 'click', 'client',
    'climb', 'clipper', 'cloakroom', 'clock', 'close', 'closet', 'cloth',
    'cloud', 'cloudy', 'clover', 'clutch', 'coach', 'coast', 'cobweb',
    'cockroach', 'cocktail', 'cocoa', 'coffee', 'coimbatore', 'collar',
    'college', 'collision', 'colombia', 'colon', 'colony', 'color',
    'column', 'columnist', 'comfort', 'comic', 'comma', 'command',
    'commission', 'committee', 'common', 'community', 'company',
    'comparison', 'competition', 'competitor', 'complain', 'composer',
    'composition', 'computer', 'condition', 'condor', 'confirmation',
    'conga', 'congo', 'conifer', 'connection', 'consonant', 'continent',
    'control', 'cooking', 'copper', 'copyright', 'cormorant', 'cornet',
    'correspondent', 'cotton', 'couch', 'cougar', 'cough', 'count',
    'country', 'course', 'court', 'cousin', 'cover', 'cowbell', 'crack',
    'cracker', 'craftsman', 'crate', 'crawdad', 'crayfish', 'crayon',
    'cream', 'creator', 'creature', 'credit', 'creditor', 'creek',
    'cricket', 'crime', 'criminal', 'crocodile', 'crocus', 'croissant',
    'crook', 'cross', 'crowd', 'crown', 'crush', 'cuban', 'cucumber',
    'cultivator', 'cultural', 'cupboard', 'cupcake', 'curler', 'currency',
    'current', 'curtain', 'curve', 'cushion', 'custard', 'customer',
    'cuticle', 'cycle', 'cyclone', 'cylinder', 'cymbal', 'daffodil',
    'dahlia', 'daisy', 'damage', 'dance', 'dancer', 'danger', 'daniel',
    'dashboard', 'database', 'daughter', 'david', 'deadline', 'death',
    'deborah', 'debtor', 'decade', 'december', 'decimal', 'decision',
    'decrease', 'dedication', 'defense', 'deficit', 'degree', 'delete',
    'delivery', 'democratic', 'denim', 'dentist', 'deodorant',
    'department', 'deposit', 'description', 'desert', 'design', 'desire',
    'dessert', 'destruction', 'detail', 'detective', 'development',
    'diamond', 'diaphragm', 'dibble', 'dictionary', 'dietician',
    'difference', 'different', 'difficult', 'digestion', 'digger',
    'digital', 'dimple', 'dinghy', 'dinner', 'dinosaur', 'diploma',
    'dipstick', 'direction', 'disadvantage', 'discovery', 'discussion',
    'disease', 'disgust', 'distance', 'distribution', 'distributor',
    'diving', 'division', 'divorced', 'doctor', 'dogsled', 'dollar',
    'dolphin', 'domain', 'donald', 'donkey', 'donna', 'dorothy',
    'double', 'doubt', 'downtown', 'dragon', 'dragonfly', 'drain',
    'drake', 'drama', 'drawbridge', 'drawer', 'dream', 'dredger', 'dress',
    'dresser', 'dressing', 'drill', 'drink', 'drive', 'driver', 'driving',
    'drizzle', 'dryer', 'duckling', 'dugout', 'dungeon', 'eagle', 'early',
    'earth', 'earthquake', 'economic', 'edger', 'editor', 'editorial',
    'education', 'edward', 'effect', 'eggnog', 'eggplant', 'egypt',
    'eight', 'elbow', 'element', 'elephant', 'elizabeth', 'ellipse',
    'emery', 'employee', 'employer', 'encyclopedia', 'enemy', 'energy',
    'engine', 'engineer', 'engineering', 'english', 'enquiry', 'entire',
    'entrance', 'environment', 'environmental', 'epoch', 'epoxy',
    'equinox', 'equipment', 'error', 'estimate', 'ethernet', 'ethiopia',
    'euphonium', 'europe', 'evening', 'event', 'examination', 'example',
    'exchange', 'exclamation', 'exhaust', 'ex-husband', 'existence',
    'expansion', 'experience', 'expert', 'explain', 'explanation',
    'ex-wife', 'eyebrow', 'eyelash', 'eyeliner', 'facilities',
    'factory', 'fahrenheit', 'fairies', 'family', 'farmer', 'father',
    'father-in-law', 'faucet', 'feast', 'feather', 'feature', 'february',
    'fedelini', 'federal', 'feedback', 'feeling', 'felony', 'female',
    'fender', 'ferry', 'ferryboat', 'fertilizer', 'fiber', 'fiberglass',
    'fibre', 'fiction', 'field', 'fifth', 'fight', 'fighter', 'final',
    'financial', 'finger', 'finish', 'fired', 'fireman', 'fireplace',
    'firewall', 'fisherman', 'flame', 'flare', 'flavor', 'flesh',
    'flight', 'flock', 'flood', 'floor', 'flower', 'flugelhorn', 'flute',
    'football', 'footnote', 'force', 'forecast', 'forehead', 'foreign',
    'forest', 'forgery', 'forget', 'format', 'fortnight', 'foundation',
    'fountain', 'foxglove', 'fragrance', 'frame', 'france', 'freckle',
    'freeze', 'freezer', 'freighter', 'french', 'freon', 'friction',
    'friday', 'fridge', 'friend', 'front', 'frost', 'frown', 'fruit',
    'furniture', 'galley', 'gallon', 'gander', 'garage', 'garden',
    'garlic', 'gasoline', 'gateway', 'gauge', 'gazelle', 'gearshift',
    'geese', 'gemini', 'gender', 'general', 'geography', 'geology',
    'geometry', 'george', 'geranium', 'german', 'germany', 'ghana',
    'ghost', 'giant', 'giraffe', 'girdle', 'gladiolus', 'glass', 'glider',
    'gliding', 'glockenspiel', 'glove', 'goldfish', 'gondola', 'good-bye',
    'goose', 'gore-tex', 'gorilla', 'gosling', 'government', 'governor',
    'grade', 'grain', 'granddaughter', 'grandfather', 'grandmother',
    'grandson', 'grape', 'graphic', 'grass', 'grasshopper', 'grease',
    'great', 'great-grandfather', 'great-grandmother', 'greece', 'greek',
    'green', 'grenade', 'grill', 'ground', 'group', 'grouse', 'growth',
    'guarantee', 'guatemalan', 'guide', 'guilty', 'guitar', 'gymnast',
    'hacksaw', 'haircut', 'half-brother', 'half-sister', 'halibut',
    'hallway', 'hamburger', 'hammer', 'hamster', 'handball', 'handicap',
    'handle', 'handsaw', 'happy', 'harbor', 'hardboard', 'hardcover',
    'hardhat', 'hardware', 'harmonica', 'harmony', 'headlight',
    'headline', 'health', 'hearing', 'heart', 'heaven', 'hedge', 'height',
    'helen', 'helicopter', 'helium', 'helmet', 'heron', 'herring',
    'hexagon', 'himalayan', 'hippopotamus', 'history', 'hobbies',
    'hockey', 'holiday', 'honey', 'horse', 'hospital', 'hourglass',
    'house', 'hovercraft', 'hubcap', 'human', 'humidity', 'humor',
    'hurricane', 'hyacinth', 'hydrant', 'hydrofoil', 'hydrogen', 'hyena',
    'hygienic', 'icebreaker', 'icicle', 'ikebana', 'illegal', 'important',
    'imprisonment', 'improvement', 'impulse', 'income', 'increase',
    'index', 'india', 'indonesia', 'industry', 'innocent', 'input',
    'insect', 'instruction', 'instrument', 'insulation', 'insurance',
    'interactive', 'interest', 'international', 'internet', 'interviewer',
    'intestine', 'invention', 'inventory', 'invoice', 'island', 'israel',
    'italian', 'italy', 'jacket', 'jaguar', 'james', 'january', 'japan',
    'japanese', 'jasmine', 'jason', 'jeans', 'jelly', 'jellyfish',
    'jennifer', 'jewel', 'jogging', 'joseph', 'journey', 'judge',
    'juice', 'jumbo', 'jumper', 'justice', 'kamikaze', 'kangaroo',
    'karate', 'karen', 'kayak', 'kendo', 'kenneth', 'kenya', 'ketchup',
    'kettle', 'kettledrum', 'kevin', 'keyboard', 'keyboarding', 'kidney',
    'kilogram', 'kilometer', 'kimberly', 'kitchen', 'kitten', 'kitty',
    'knickers', 'knife', 'knight', 'knowledge', 'kohlrabi', 'korean',
    'laborer', 'ladybug', 'landmine', 'language', 'larch', 'large',
    'lasagna', 'latency', 'latex', 'lathe', 'laugh', 'laundry', 'laura',
    'lawyer', 'layer', 'learn', 'learning', 'leather', 'leave', 'legal',
    'lemonade', 'lentil', 'leopard', 'letter', 'lettuce', 'level',
    'libra', 'library', 'license', 'light', 'lightning', 'likely',
    'lilac', 'limit', 'linda', 'linen', 'lipstick', 'liquid', 'liquor',
    'listen', 'literature', 'litter', 'little', 'liver', 'lizard',
    'llama', 'lobster', 'local', 'locket', 'locust', 'lotion', 'lumber',
    'lunch', 'lunchroom', 'lunge', 'luttuce', 'lycra', 'lyocell', 'lyric',
    'macaroni', 'machine', 'macrame', 'madurai', 'magazine', 'magic',
    'magician', 'mailbox', 'mailman', 'major', 'makeup', 'malaysia',
    'mallet', 'manager', 'mandolin', 'manicure', 'maple', 'maraca',
    'marble', 'march', 'margaret', 'margin', 'maria', 'marimba', 'market',
    'married', 'mascara', 'match', 'mattock', 'mayonnaise', 'measure',
    'mechanic', 'medical', 'medicine', 'meeting', 'melody', 'memory',
    'mercury', 'message', 'metal', 'meteorology', 'meter', 'methane',
    'mexican', 'mexico', 'michael', 'michelle', 'microwave', 'middle',
    'military', 'milkshake', 'millennium', 'millimeter', 'millisecond',
    'mimosa', 'minibus', 'mini-skirt', 'minister', 'minute', 'mirror',
    'missile', 'mistake', 'mitten', 'modem', 'monday', 'money', 'monkey',
    'month', 'morning', 'morocco', 'mosque', 'mosquito', 'mother',
    'mother-in-law', 'motion', 'motorboat', 'motorcycle', 'mountain',
    'mouse', 'moustache', 'mouth', 'multi-hop', 'multimedia', 'muscle',
    'museum', 'music', 'musician', 'mustard', 'myanmar', 'nancy',
    'napkin', 'narcissus', 'nation', 'national', 'natural', 'needle',
    'nepal', 'nephew', 'nerve', 'network', 'newsprint', 'newsstand',
    'nickel', 'niece', 'nigeria', 'night', 'nitrogen', 'noise',
    'noodle', 'north', 'north-america', 'norwegian', 'notebook',
    'notify', 'novel', 'november', 'number', 'numeric', 'nurse',
    'nylon', 'oatmeal', 'objective', 'observation', 'occupation',
    'ocean', 'ocelot', 'octagon', 'octave', 'october', 'octopus',
    'odometer', 'offence', 'offer', 'office', 'olive', 'onion',
    'opera', 'operation', 'ophthalmologist', 'opinion', 'option',
    'orange', 'orchestra', 'orchid', 'order', 'organ', 'organisation',
    'organise', 'organization', 'ornament', 'ostrich', 'otter', 'ounce',
    'output', 'outrigger', 'overcoat', 'owner', 'oxygen', 'oyster',
    'package', 'packet', 'paint', 'pajama', 'pakistan', 'pamphlet',
    'pancake', 'pancreas', 'panda', 'pansy', 'panther', 'panties',
    'pantry', 'pants', 'panty', 'pantyhose', 'paper', 'paperback',
    'parade', 'parallelogram', 'parcel', 'parent', 'parentheses',
    'parrot', 'parsnip', 'particle', 'partner', 'partridge', 'party',
    'passbook', 'passenger', 'passive', 'pasta', 'paste', 'pastor',
    'pastry', 'patch', 'patient', 'patio', 'patricia', 'payment',
    'peace', 'peanut', 'pedestrian', 'pediatrician', 'peer-to-peer',
    'pelican', 'penalty', 'pencil', 'pendulum', 'pentagon', 'peony',
    'pepper', 'perch', 'perfume', 'period', 'periodical', 'peripheral',
    'permission', 'persian', 'person', 'personal', 'pharmacist',
    'pheasant', 'philippines', 'philosophy', 'phone', 'physical',
    'physician', 'piano', 'piccolo', 'pickle', 'picture', 'pigeon',
    'pillow', 'pilot', 'pimple', 'pisces', 'pizza', 'place', 'plain',
    'plane', 'planet', 'plant', 'plantation', 'plaster', 'plasterboard',
    'plastic', 'plate', 'platinum', 'playground', 'playroom',
    'pleasure', 'plier', 'plough', 'plywood', 'pocket', 'point', 'poison',
    'poland', 'police', 'policeman', 'polish', 'political', 'politician',
    'pollution', 'polyester', 'popcorn', 'poppy', 'popular', 'population',
    'porch', 'porcupine', 'porter', 'position', 'possibility', 'possible',
    'postage', 'postbox', 'potato', 'poultry', 'pound', 'powder', 'power',
    'precipitation', 'preface', 'prepared', 'pressure', 'price', 'priest',
    'print', 'printer', 'prison', 'private', 'probation', 'process',
    'processing', 'produce', 'product', 'production', 'professor',
    'profit', 'promotion', 'propane', 'property', 'prose', 'prosecution',
    'protest', 'protocol', 'pruner', 'psychiatrist', 'psychology',
    'ptarmigan', 'public', 'puffin', 'pumpkin', 'punch', 'punishment',
    'puppy', 'purchase', 'purple', 'purpose', 'pyjama', 'pyramid',
    'quail', 'quality', 'quart', 'quarter', 'quartz', 'queen', 'question',
    'quicksand', 'quiet', 'quill', 'quilt', 'quince', 'quiver',
    'quotation', 'rabbi', 'rabbit', 'racing', 'radar', 'radiator',
    'radio', 'radish', 'railway', 'rainbow', 'raincoat', 'rainstorm',
    'ramie', 'random', 'range', 'raven', 'ravioli', 'rayon', 'reaction',
    'reading', 'ready', 'reason', 'receipt', 'recent', 'recess',
    'record', 'recorder', 'rectangle', 'reduction', 'refrigerator',
    'refund', 'regret', 'reindeer', 'relation', 'relative', 'religion',
    'religious', 'relish', 'reminder', 'repair', 'replace', 'reply',
    'report', 'representative', 'request', 'resolution', 'respect',
    'responsibility', 'restaurant', 'result', 'retailer', 'revolve',
    'revolver', 'reward', 'rhinoceros', 'rhythm', 'richard', 'riddle',
    'rifle', 'right', 'river', 'riverbed', 'roadway', 'roast', 'robert',
    'robin', 'rocket', 'romania', 'romanian', 'ronald', 'rooster',
    'rotate', 'route', 'router', 'rowboat', 'rubber', 'rugby', 'russia',
    'russian', 'rutabaga', 'sagittarius', 'sailboat', 'sailor', 'salad',
    'salary', 'salesman', 'salmon', 'sampan', 'samurai', 'sandra',
    'sandwich', 'santa', 'sarah', 'sardine', 'satin', 'saturday',
    'sauce', 'saudi-arabia', 'sausage', 'saxophone', 'scale', 'scallion',
    'scanner', 'scarecrow', 'scarf', 'scene', 'scent', 'schedule',
    'school', 'science', 'scissors', 'scooter', 'scorpio', 'scorpion',
    'scraper', 'screen', 'screw', 'screwdriver', 'seagull', 'seaplane',
    'search', 'seashore', 'season', 'second', 'secretary', 'secure',
    'security', 'seeder', 'segment', 'select', 'selection', 'semicircle',
    'semicolon', 'sense', 'sentence', 'separated', 'september', 'serious',
    'servant', 'server', 'session', 'shade', 'shadow', 'shake', 'shallot',
    'shame', 'shampoo', 'shape', 'share', 'shark', 'sharon', 'shears',
    'sheep', 'sheet', 'shelf', 'shell', 'shield', 'shingle', 'shirt',
    'shock', 'shoemaker', 'short', 'shorts', 'shoulder', 'shovel',
    'shrimp', 'shrine', 'siamese', 'siberian', 'sideboard', 'sidecar',
    'sidewalk', 'signature', 'significant', 'silica', 'silver', 'similar',
    'simple', 'singer', 'single', 'sister', 'sister-in-law', 'skate',
    'skiing', 'skill', 'skirt', 'slash', 'slave', 'sleep', 'sleet',
    'slice', 'slime', 'slipper', 'slope', 'small', 'smash', 'smell',
    'smile', 'smoke', 'snail', 'snake', 'sneeze', 'snowboarding',
    'snowflake', 'snowman', 'snowplow', 'snowstorm', 'soccer',
    'social', 'society', 'sociology', 'softball', 'softdrink',
    'software', 'soldier', 'soprano', 'sound', 'sousaphone', 'south-africa',
    'south-america', 'soybean', 'space', 'spade', 'spaghetti',
    'spain', 'spandex', 'spark', 'sparrow', 'speak', 'spear', 'special',
    'specialist', 'speedboat', 'spell', 'spend', 'sphere', 'sphynx',
    'spider', 'spike', 'spinach', 'spleen', 'sponge', 'spoon', 'spring',
    'sprout', 'spruce', 'square', 'squash', 'squid', 'squirrel',
    'stage', 'staircase', 'stamp', 'stand', 'start', 'starter', 'state',
    'statement', 'station', 'statistic', 'steam', 'steel', 'step-aunt',
    'step-brother', 'step-daughter', 'stepdaughter', 'step-father',
    'step-grandfather', 'step-grandmother', 'step-mother', 'stepmother',
    'step-sister', 'step-son', 'stepson', 'step-uncle', 'steven',
    'stick', 'stinger', 'stitch', 'stock', 'stocking', 'stomach', 'stone',
    'stool', 'stopsign', 'stopwatch', 'store', 'storm', 'story', 'stove',
    'stranger', 'straw', 'stream', 'street', 'streetcar', 'stretch',
    'string', 'strong', 'structure', 'study', 'sturgeon', 'submarine',
    'substance', 'subway', 'succeed', 'success', 'sudan', 'suede',
    'sugar', 'suggestion', 'summer', 'sunday', 'sundial', 'sunflower',
    'sunshine', 'supermarket', 'supply', 'support', 'surfboard',
    'surgeon', 'surname', 'surprise', 'susan', 'sushi', 'swallow',
    'swamp', 'sweater', 'sweatshirt', 'sweatshop', 'swedish', 'sweets',
    'swimming', 'swing', 'swiss', 'switch', 'sword', 'swordfish',
    'sycamore', 'syria', 'syrup', 'system', 'table', 'tablecloth',
    'tabletop', 'tachometer', 'tadpole', 'tailor', 'taiwan', 'tanker',
    'tanzania', 'target', 'taste', 'taurus', 'taxicab', 'teach',
    'teacher', 'teaching', 'technician', 'teeth', 'television', 'teller',
    'temper', 'temperature', 'temple', 'tempo', 'tendency', 'tennis',
    'tenor', 'territory', 'textbook', 'texture', 'thailand', 'theater',
    'theory', 'thermometer', 'thing', 'think', 'thistle', 'thomas',
    'thought', 'thread', 'thrill', 'throat', 'throne', 'thumb', 'thunder',
    'thunderstorm', 'thursday', 'ticket', 'tiger', 'tights', 'timbale',
    'timer', 'timpani', 'titanium', 'title', 'toast', 'toenail',
    'toilet', 'tomato', 'tom-tom', 'tongue', 'tooth', 'toothbrush',
    'toothpaste', 'tornado', 'tortellini', 'tortoise', 'touch', 'tower',
    'tractor', 'trade', 'traditional', 'traffic', 'trail', 'train',
    'tramp', 'transaction', 'translate', 'transmission', 'transport',
    'trapezoid', 'travel', 'treatment', 'trial', 'triangle', 'trick',
    'trigonometry', 'trombone', 'trouble', 'trousers', 'trout', 'trowel',
    'truck', 'trumpet', 'trunk', 't-shirt', 'tsunami', 'tuesday',
    'tugboat', 'tulip', 'turkey', 'turkish', 'turnip', 'turnover',
    'turret', 'turtle', 'twilight', 'twine', 'twist', 'typhoon',
    'tyvek', 'uganda', 'ukraine', 'ukrainian', 'umbrella', 'uncle',
    'underclothes', 'underpants', 'undershirt', 'understand', 'underwear',
    'united-kingdom', 'unshielded', 'utensil', 'uzbekistan', 'vacation',
    'vacuum', 'valley', 'value', 'various', 'vault', 'vegetable',
    'vegetarian', 'velvet', 'venezuela', 'venezuelan', 'verdict',
    'vermicelli', 'verse', 'vessel', 'veterinarian', 'vibraphone',
    'vietnam', 'vinyl', 'viola', 'violet', 'violin', 'virgo', 'viscose',
    'vision', 'visitor', 'voice', 'volcano', 'volleyball', 'voyage',
    'vulture', 'waiter', 'waitress', 'wallaby', 'wallet', 'walrus',
    'washer', 'waste', 'watch', 'watchmaker', 'water', 'waterfall',
    'wealth', 'weapon', 'weasel', 'weather', 'wedge', 'wednesday',
    'weeder', 'weight', 'whale', 'wheel', 'whiskey', 'whistle', 'white',
    'whole', 'wholesaler', 'whorl', 'wilderness', 'william', 'willow',
    'windchime', 'window', 'windscreen', 'windshield', 'winter', 'witch',
    'withdrawal', 'witness', 'woman', 'women', 'woolen', 'workshop',
    'worry', 'wound', 'wrecker', 'wrench', 'wrinkle', 'wrist', 'write',
    'writer', 'wrong', 'xylophone', 'yacht', 'yellow', 'yogurt', 'young',
    'yugoslavian', 'zebra', 'zephyr', 'zipper', 'zoology'
]

def generate(length=40):
    """Generate password of size length."""
    minl = int(length * 0.9)
    maxl = int(length * 1.1)

    passwd = ''

    while len(passwd) < minl:
        word = random.choice(WORDS)
        if len(passwd) + len(word) > maxl:
            continue
        else:
            passwd = passwd + '-' + word

    return passwd[1:].strip()

if __name__ == '__main__':
    if len(sys.argv) == 1:
        print(generate())
    else:
        print(generate(int(sys.argv[1])))
