# vim: ft=conf fdm=marker et sts=2 sw=2
#
# General degoogle list for Android devices.  Comment out
# apps (e.g., Maps, Play Store, etc.) that ought to be kept.
#
# Updated: 2025-10-23 23:08 IST

# Essential apps.
# com.google.android.apps.maps # Google Maps

# Essential on many phones and not-very intrusive apps.
# NOTE: Keep for noob devices (e.g., parents' phones).
com.google.android.apps.messaging # Messaging
com.google.android.apps.photos # Google Photos (gallery app)
com.google.android.contacts # Contacts
com.google.android.dialer # Phone
com.google.android.inputmethod.latin # Gboard (Google Keyboard)
com.google.android.apps.wellbeing # Digital Wellbeing
com.google.android.calendar # Calendar app
com.google.android.apps.nbu.files # File browser
com.google.android.calculator # Calculator
com.google.android.apps.docs # Google Drive

# Somewhat essential, but intrusive apps.
# NOTE: Keep for noob devices (e.g., parents' phones).
com.android.vending # Play Store
com.android.chrome # Google Chrome
com.google.android.apps.nbu.paisa.user # Google Pay
com.google.android.gm # Gmail
com.google.android.youtube # YouTube
com.google.android.backuptransport # Allow apps to backup to Google servers

# Other non-essential and intrusive apps.
# Lens requires the Google app to function.
com.google.ar.lens # Google Lens
com.google.android.googlequicksearchbox # Google

# OEM apps, but related to Google.
com.android.hotwordenrollment.google
com.android.hotwordenrollment.okgoogle
com.android.hotwordenrollment.xgoogle

# Text-to-speech.
com.google.android.tts
