com.facebook.appmanager
com.facebook.katana
com.facebook.services
com.facebook.system
com.microsoft.appmanager
com.microsoft.deviceintegrationservice
com.microsoftsdk.crossdeviceservicebroker
com.microsoft.office.excel
com.microsoft.office.powerpoint
com.microsoft.office.word
com.microsoft.skydrive
com.netflix.mediaclient
com.netflix.partner.activation
com.microsoft.office.outlook
com.sec.android.app.sbrowser
com.sec.android.app.shealth
com.microsoft.skydrive
com.microsoft.appmanager
com.spotify.music
