# realmi debloat list.
# 2025-10-25 23:39 IST
com.android.apps.tag
com.android.wallpaper.livepicker
com.android.wallpaper.livepicker.overlay
com.coloros.activation
com.coloros.compass2
com.coloros.note
com.coloros.oshare
com.coloros.wifibackuprestore
com.fido.asm
com.heytap.market
com.heytap.usercenter
com.oplus.apprecover
com.oplus.cast
com.oplus.multiapp
com.oplus.pay
com.oplus.screenrecorder
com.oplus.sos
com.oplus.synergy
com.oplus.themestore
com.oplus.wallpapers
com.realme.movieshot

# Maybe keep?
com.oplus.melody # earphone
com.coloros.soundrecorder
com.coloros.weather2
com.coloros.weather.service
