# TCL Google TV debloater list
# Tested on TCL 32V5C in October 2025.

com.android.captiveportallogin
com.android.cts.ctsshim
com.android.sharedstoragebackup
com.android.wallpaperbackup
com.google.android.ext.shared
com.google.android.webview
com.google.android.apps.safetyhub

com.google.android.tvrecommendations # Android TV Recommendations
com.google.android.leanbacklauncher.recommendations # Google Shop Row
com.google.android.gms.cast.receiver # Chromecast Built-In
com.google.android.backdrop # Google Backdrop
com.google.android.videos # Google Play Movies & TV
com.google.android.play.games # Google Play Games
com.google.android.apps.mediashell # Google Mediashell
com.google.android.apps.nbu.smartconnect.tv # Google Smart Connect
com.google.android.feedback # Google Feedback
com.google.android.onetimeinitializer # One-Time Initializer
com.google.android.syncadapters.calendar # Calendar Sync Adapter
com.google.android.partnersetup # Google Partner Setup
com.android.egg # Android Easter Egg
com.android.printspooler # Print Spooler
com.google.android.marvin.talkback # TalkBack (Accessibility)
com.android.dreams.basic # Android Screensaver
com.google.android.apps.tv.dreamx # Android screensaver
com.android.providers.calendar # Calendar Provider
com.android.providers.contacts # Contacts Provider
com.android.providers.userdictionary # User Dictionary
com.tcl.gallery # TCL Gallery
com.tcl.notereminder # TCL Notes & Reminders
com.tcl.messagebox # TCL MessageBox
com.tcl.guard # TCL Antivirus (Guard)
com.tcl.tvweishi # TCL Antivirus Overlay
com.tcl.appmarket2 # TCL App Market
com.tcl.esticker # TCL Stickers
com.tcl.pvr.pvrplayer # TCL PVR Player
com.tcl.videoplayer # TCL Video Player
com.tcl.overseasappshow # TCL Overseas App Ads
com.tcl.bootadservice # TCL Boot Ads
com.tcl.dashboard # TCL Dashboard
com.netflix.ninja # Netflix TV App
com.aos.aostv # AOS TV
uk.co.freeview.explore # Freeview Explore
uk.co.freeview.onnow # Freeview On Now"

com.google.android.gms.cast.receiver # Chromecast Built-In
com.google.android.videos # Google Play Movies & TV
com.google.android.tvrecommendations # Android TV Recommendations
com.tcl.usercenter2 # TCL Launcher
com.tcl.usercenter # TCL User Center
com.tcl.browser # TCL Web Browser
com.tcl.notereminder # Notes and Reminders
com.tcl.gallery # Gallery App
com.netflix.ninja # Netflix TV App
uk.co.freeview.explore # Freeview Explore
com.aos.aostv # AOS TV
com.google.android.googlequicksearchbox # Google Assistant
